test start-deploy

diff --git a/.github/workflows/instance1.yml b/.github/workflows/instance1.yml
--- a/.github/workflows/instance1.yml
+++ b/.github/workflows/instance1.yml
@@ -21,9 +21,57 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Check and Create java_files directory
+        run: |
+          USER_NAME=$(whoami)
+          if [ ! -d "/home/$USER_NAME/java_files" ]; then
+              # If the java_files folder does not exist, create it
+              mkdir -p "/home/$USER_NAME/java_files"
+              echo "java_files folder created in /home/$USER_NAME"
+          else
+              echo "java_files folder already exists in /home/$USER_NAME"
+          fi
+
+
+      - name: Backup Old Jar
+        run: |
+          sudo pwd
+          sleep 3
+          USER_NAME=$(whoami)
+          JAR_FILE=$(find "/home/$USER_NAME/java_files" -maxdepth 1 -name "*.jar" ! -name "*_old*" -print -quit)
+          if [ -n "$JAR_FILE" ]; then
+            DESTINY="/home/$USER_NAME/java_files"
+            JAR_FILENAME=$(basename "$JAR_FILE")
+            NEW_JAR_FILENAME="${JAR_FILENAME%.*}_old.jar"
+            sudo cp "$JAR_FILE" "$DESTINY/$NEW_JAR_FILENAME"
+            echo "Created copy of $JAR_FILENAME === $NEW_JAR_FILENAME in $DESTINY"
+          else
+            echo "JAR file not found."
+          fi
+
+      - name: Backup Crontab
+        run: |
+          USER_NAME=$(whoami)
+          DESTINY="/home/$USER_NAME/java_files"
+          crontab -l > $DESTINY/crontab_backup
+
       - name: Build with Maven
         run: >
           mvn package assembly:single -DskipTests=true
+
+      - name: Copy Post Build Jar File
+        run: |
+          USER_NAME=$(whoami)
+          JAR_FILE=$(find "$(pwd)/target" -maxdepth 1 -name "*.jar" ! -name "*SNAPSHOT*" -print -quit)
+          if [ -n "$JAR_FILE" ]; then
+            DESTINY="/home/$USER_NAME/java_files"
+            JAR_FILENAME=$(basename "$JAR_FILE")
+            NEW_JAR_FILENAME="${JAR_FILENAME%.*}_old.jar"
+            sudo cp "$JAR_FILE" "$DESTINY"
+            echo "Created copy of $JAR_FILENAME === $NEW_JAR_FILENAME in $DESTINY"
+          else
+            echo "JAR file not found."
+          fi
 
       - name: Kill Port
         run: |
@@ -37,10 +85,100 @@ jobs:
           fi
 
       - name: Execute Jar File
+        run: |
+          sleep 3
+          USER_NAME=$(whoami)
+          JAR_FILE=$(find "/home/$USER_NAME/java_files" -maxdepth 1 -name "*.jar" ! -name "*_old*" -print -quit)
+          if [ -n "$JAR_FILE" ]; then
+            JAR_FILENAME=$(basename "$JAR_FILE")
+            sudo AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
+            SERVER_PORT=${{ vars.VARIABLE_PORT_SERVER }} \
+            ANNOTATION_TEST_1=${{ secrets.ANNOTATION_TEST_1 }} \
+            ANNOTATION_TEST_2=${{ secrets.ANNOTATION_TEST_2 }} \
+            ANNOTATION_TEST_3=${{ secrets.ANNOTATION_TEST_3 }} \
+            ANNOTATION_TEST_4=${{ secrets.ANNOTATION_TEST_4 }} \
+            ANNOTATION_TEST_5=${{ secrets.ANNOTATION_TEST_5 }} \
+            ANNOTATION_TEST_6=${{ vars.VARIABLE_TEST }} \
+            java -jar "$JAR_FILE" >> logs &
+          else
+            echo "No jar file found."
+            exit 1
+          fi
+
+      - name: Logs
+        run: |
+          sleep 10 &&
+          cat logs
+
+
+      - name: CheckStatus
+        id: check-status
+        run: |
+          sleep 2 &&
+          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ vars.VARIABLE_PORT_SERVER }}/ping) &&
+          echo "response-status=$response" >> $GITHUB_OUTPUT
+          if [ "$response" = "200" ]; then
+            echo "Server is running."
+          else
+            echo "Server not available! Status: $response" &&
+            cat logs
+          fi
+
+      - name: ==== ROLLBACK ACTION ====
+        if: ${{ steps.check-status.outputs.response-status != 200 }}
+        run: |
+          set +e
+          USER_NAME=$(whoami)
+          if [ -f "/home/$USER_NAME/java_files/crontab_backup" ]; then
+              echo "crontab_backup file found."
+
+              JAR_FILE=$(find "/home/$USER_NAME/java_files" -maxdepth 1 -name "*_old.jar")
+              if [ -n "$JAR_FILE" ]; then
+                  echo "Old JAR file found: $JAR_FILE"
+
+                  NEW_JAR_FILE="${JAR_FILE%_old.jar}.jar"
+                  mv "$JAR_FILE" "$NEW_JAR_FILE"
+                  echo "Removing _old suffix from JAR file: $NEW_JAR_FILE"
+          
+                  if sudo fuser -s ${{ vars.VARIABLE_PORT_SERVER }}/tcp; then
+                    echo "Port ${{ vars.VARIABLE_PORT_SERVER }} (TCP) is in use. Killing the process..."
+                    sudo fuser -k -TERM -k ${{ vars.VARIABLE_PORT_SERVER }}/tcp
+                    eval "$(sed 's/@reboot //g' "/home/$USER_NAME/java_files/crontab_backup") &"
+                    sleep 10
+                    eval "cat logs"
+                  else
+                    eval "$(sed 's/@reboot //g' "/home/$USER_NAMEs/java_files/crontab_backup") &"
+                    sleep 10
+                    eval "cat logs"
+                  fi
+
+              else
+                  echo "Old JAR file not found."
+              fi
+          else
+              echo "crontab_backup file not found."
+          fi
+          if [[ $exit_code -eq 143 ]]; then
+            echo "Ignore Exit 143."
+            exit 0
+          elif [[ $exit_code -ne 0 ]]; then
+            echo "Error: $exit_code"
+            exit $exit_code 
+          fi
+
+
+      - name: Crontab Clear
+        if: ${{ steps.check-status.outputs.response-status == 200 }}
         run: >
-          sleep 3 &&
-          JAR_PATH=$(pwd) &&
-          sudo
+          echo "" | crontab -
+
+      - name: Crontab Configuration
+        if: ${{ steps.check-status.outputs.response-status == 200 }}
+        run: >
+          USER_NAME=$(whoami) &&
+          JAR_FILE=$(find "/home/$USER_NAME/java_files" -maxdepth 1 -name "*.jar" ! -name "*_old*" -print -quit) &&
+          echo "@reboot
+          sudo 
           AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
           SERVER_PORT=${{ vars.VARIABLE_PORT_SERVER }}
           ANNOTATION_TEST_1=${{ secrets.ANNOTATION_TEST_1 }}
@@ -49,42 +187,5 @@ jobs:
           ANNOTATION_TEST_4=${{ secrets.ANNOTATION_TEST_4 }}
           ANNOTATION_TEST_5=${{ secrets.ANNOTATION_TEST_5 }}
           ANNOTATION_TEST_6=${{ vars.VARIABLE_TEST }}
-          java -jar "$JAR_PATH"/target/auto-deploy.jar >> logs &
-
-      - name: Logs
-        run: |
-          sleep 15 &&
-          cat logs
-
-
-      - name: Check Status
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:${{ vars.VARIABLE_PORT_SERVER }}/ping) &&
-          if [ "$response" = "200" ]; then
-            echo "Server is running."
-          else
-            echo "Server not available! Status: $response" &&
-            cat logs
-            exit 1
-          fi
-
-
-      - name: Crontab Clear
-        run: >
-          echo "" | crontab -
-
-      - name: Crontab Configuration
-        run: >
-          JAR_PATH=$(pwd) &&
-          echo "@reboot
-          sudo
-          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
-          SERVER_PORT=${{ vars.VARIABLE_PORT_SERVER }}
-          ANNOTATION_TEST_1=${{ secrets.ANNOTATION_TEST_1 }} 
-          ANNOTATION_TEST_2=${{ secrets.ANNOTATION_TEST_2 }}
-          ANNOTATION_TEST_3=${{ secrets.ANNOTATION_TEST_3 }}
-          ANNOTATION_TEST_4=${{ secrets.ANNOTATION_TEST_4 }}
-          ANNOTATION_TEST_5=${{ secrets.ANNOTATION_TEST_5 }}
-          ANNOTATION_TEST_6=${{ vars.VARIABLE_TEST }}
-          java -jar "$JAR_PATH"/target/auto-deploy.jar >> logs"
-          | crontab -
+          java -jar \"$JAR_FILE\" >> logs
+          " | crontab -
