testing GitHub secrets

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -51,3 +51,12 @@ jobs:
         sudo kill -9 `sudo lsof -t -i:8080` &
         sudo java -jar /home/ec2-user/actions-runner/_work/auto-deploy-test/auto-deploy-test/target/auto-deploy.jar >> logs &
         tail -f logs
+    - name: Check Status
+      run: |
+        RESPONSE=$(curl -s -w "%{http_code}" "http://localhost:8080/ping")
+        if [ "$RESPONSE" = "200" ]; then
+        echo "API response: $RESPONSE"
+        else
+        echo "API request failed"
+        exit 1
+        fi
