testing GitHub secrets

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -50,4 +50,11 @@ jobs:
         echo $MY_SECRET_TEST $AWS_ACCESS_KEY_ID $AWS_SECRET_KEY $AWS_REGION &
         sudo kill -9 `sudo lsof -t -i:8080` &
         sudo java -jar /home/ec2-user/actions-runner/_work/auto-deploy-test/auto-deploy-test/target/auto-deploy.jar >> logs &
+        RESPONSE=$(curl -s -w "%{http_code}" "http://localhost:8080/hello")
+        if [ "$RESPONSE" = "200" ]; then
+        echo "API response: $RESPONSE"
+        else
+        echo "API request failed"
+        exit 1
+        fi
         echo $MY_SECRET_TEST $AWS_ACCESS_KEY_ID $AWS_SECRET_KEY $AWS_REGION &
