testing GitHub secrets

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -53,9 +53,9 @@ jobs:
     - name: Check Status
       run: |
         RESPONSE=$(curl -s -w "%{http_code}" "http://localhost:8080/ping")
-        if [ "$RESPONSE" = "200" ]; then
-        echo "API response: $RESPONSE" &
+        if [[ "$RESPONSE" == "200" ]]; then
+          echo "Request succeeded. Continuing the workflow..."
         else
-        echo "API request failed"
-        exit 1
+          echo "Request failed with status code $RESPONSE. Stopping the workflow."
+          exit 1
         fi
