New Instance Configuration

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -6,7 +6,7 @@
 # separate terms of service, privacy policy, and support
 # documentation.
 
-name: Instance 1
+name: Runner Balancer
 
 on:
   push:
@@ -14,20 +14,69 @@ on:
 
 jobs:
   build-runner1:
-    runs-on: runner_2
+    runs-on: runner_0
     if: github.ref == 'refs/heads/master'
 
     steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: '11'
+          distribution: 'temurin'
+          cache: maven
+      - name: Build with Maven
+        run: |
+          mvn package assembly:single -Dspring.profiles.active=local
+      - name: Kill Port
+        run: |
+          if sudo fuser -s 8080/tcp; then
+            echo "Port 8080 is in use. Killing the process..."
+            sudo fuser -k 8080/tcp
+          else
+            exit 0
+          fi
+      - name: Execute Jar File
+        run: >
+          sudo
+          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
+          SERVER_PORT=${{ secrets.SERVER_PORT }}
+          ANNOTATION_TEST_1=${{ secrets.ANNOTATION_TEST_1 }} 
+          ANNOTATION_TEST_2=${{ secrets.ANNOTATION_TEST_2 }}
+          ANNOTATION_TEST_3=${{ secrets.ANNOTATION_TEST_3 }}
+          ANNOTATION_TEST_4=${{ secrets.ANNOTATION_TEST_4 }}
+          ANNOTATION_TEST_5=${{ secrets.ANNOTATION_TEST_5 }}
+          ANNOTATION_TEST_6=${{ vars.VARIABLE_TEST }}
+          java -jar /home/ec2-user/actions-runner/_work_0/auto-deploy-test/auto-deploy-test/target/auto-deploy.jar >> logs &
+      - name: ==Check Status==
+        run: |
+          sleep 10
+          if grep -q "Tomcat started on port" logs && grep -q "Started" logs; then
+            echo "Initialization success"
+            cat logs
+          else
+            echo "Initialization failed. Exiting..."
+            cat logs
+            exit 1
+          fi
       - name: Crontab Clear
         run: echo "" | crontab -
       - name: Crontab Configuration
         run: >
           echo "@reboot
-          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}"
+          AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
+          SERVER_PORT=${{ secrets.SERVER_PORT }}
+          ANNOTATION_TEST_1=${{ secrets.ANNOTATION_TEST_1 }} 
+          ANNOTATION_TEST_2=${{ secrets.ANNOTATION_TEST_2 }}
+          ANNOTATION_TEST_3=${{ secrets.ANNOTATION_TEST_3 }}
+          ANNOTATION_TEST_4=${{ secrets.ANNOTATION_TEST_4 }}
+          ANNOTATION_TEST_5=${{ secrets.ANNOTATION_TEST_5 }}
+          ANNOTATION_TEST_6=${{ vars.VARIABLE_TEST }}
+          java -jar /home/ec2-user/actions-runner/_work_0/auto-deploy-test/auto-deploy-test/target/auto-deploy.jar >> logs"
           | crontab -
 
   build-runner2:
-    runs-on: runner_1
+    runs-on: runner_2
     if: github.ref == 'refs/heads/dev'
 
     steps:
